version: '3.4'

services:
  app:
    image: node:11.15-slim
    volumes:
        - ./:/code
    command: yarn run watch
    working_dir: /code
    tty: true
  serve:
    image: python:3.6-alpine
    volumes:
      - ./:/code
    working_dir: /code/work
    command: python -m http.server
    ports:
      - "8999:8000"
    tty: true
