version: '3.4'

services:
    app:
        build: 
            context: .
            dockerfile: ./dockerfile-node-local
        working_dir: /code/dist
        command: http-server
        volumes:
            - ./:/code
        ports:
            - "8989:8080"
